CREATE TABLE raw_hamsterwheel(
    id INT NOT NULL AUTO_INCREMENT,
    time TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    magnet TINYINT(1) NOT NULL,
    PRIMARY KEY ( id )
);

CREATE TABLE closed_hamsterwheel(
    id INT NOT NULL AUTO_INCREMENT,
    time TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    magnet TINYINT(1) NOT NULL,
    PRIMARY KEY ( id )
);

CREATE TABLE log(
    id INT NOT NULL AUTO_INCREMENT,
    time TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    event VARCHAR(100) NOT NULL,
    PRIMARY KEY ( id )
);

CREATE TABLE wallet(
    id INT NOT NULL AUTO_INCREMENT,
    currency_symbol VARCHAR(50) NOT NULL,
    amount FLOAT NOT NULL,
    PRIMARY KEY ( id )
);

CREATE TABLE price(
    id INT NOT NULL AUTO_INCREMENT,
    currency_symbol VARCHAR(50) NOT NULL,
    price FLOAT NOT NULL,
    PRIMARY KEY ( id )
);


CREATE TABLE orderbook(
    id INT NOT NULL AUTO_INCREMENT,
    time TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    wallet_id INT NOT NULL,
    price FLOAT NOT NULL,
    amount FLOAT NOT NULL,
    currency VARCHAR(50) NOT NULL,
    type VARCHAR(50) NOT NULL,
    state VARCHAR(50) NOT NULL,
    PRIMARY KEY ( id ),
    FOREIGN KEY ( wallet_id ) REFERENCES wallet( id )
);

CREATE TABLE decision(
    id INT NOT NULL AUTO_INCREMENT,
    start_time TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    end_time TIMESTAMP(6),
    number_hamsterwheels INT,
    type VARCHAR(50) NOT NULL,
    status VARCHAR(100),
    result VARCHAR(50),
    PRIMARY KEY ( id )
);